# Generated by Django 4.2.1 on 2023-05-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_m7', '0002_datosusuarioextra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosusuarioextra',
            options={'ordering': ['-id_user'], 'verbose_name': 'Datos de Usuario', 'verbose_name_plural': 'Datos de Usuarios'},
        ),
    ]
